base_url = "https://travel.dabase.com"
theme = "simple-dev-blog"
title = "Kai's travel archives"
taxonomies = [ { name = "tags" } ]

[extra]
nav = [
  { name = "Backpacking blog", path = "/blog/" }
]

author = "Kai Hendry"

not_found_message = """
This is not the page you're looking for... return back to [home?](/)
"""

footer_about = """
[colophon](https://github.com/kaihendry/enemies-of-carlotta-zola)
"""
