# The URL the site will be built for
base_url = "https://travel.natalian.org"
theme = "simple-dev-blog"
taxonomies = [ { name = "tags" } ]

[extra]
nav = [
  { name = "Blog", path = "/blog/" }
]

author = "Kai Hendry"

not_found_message = """
This is not the page you're looking for... return back to [home?](/)
"""

footer_about = """
A test site by [Kai Hendry](https://hendry.iki.fi/)
"""
