on: [pull_request, push]

jobs:
  builddeploy:
    name: Build site with Zola and deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Zola
        run: sudo snap install --edge zola
      - name: Build site
        run: zola build
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.3.0
        with:
          # Your Cloudflare API Token
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env: # https://github.com/cloudflare/wrangler-action/issues/12
          USER: root
