on: [push]

jobs:
  builddeploy:
    name: Build site with Zola and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Check out IaC Cloudformation
        uses: actions/checkout@master
        with:
          repository: kaihendry/s3-cloudfront-cloudformation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: travel
          template: template.yml
          parameter-overrides: "DomainName=travel.natalian.org,AcmWildcard=arn:aws:acm:us-east-1:407461997746:certificate/8e3ee384-d4f3-47b7-b0a6-c28fa0b4a26b,HostedZone=Z2OT4MN00JO5F8"
          no-fail-on-empty-changeset: "1"
      - uses: actions/checkout@v2
        with: # for https://github.com/bennetthardwick/simple-dev-blog-zola-starter
          submodules: true
      - name: Install Zola
        run: sudo snap install --edge zola
      - name: Check for broken links
        run: zola check
      - name: Build site
        run: zola build
      - name: S3 Sync to deploy
        run: aws s3 sync --acl public-read --delete public/ s3://travel.natalian.org
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "$(aws cloudfront list-distributions --query "DistributionList.Items[*].{Alias:Aliases.Items[0],Id:Id}[?Alias=='travel.natalian.org'].Id" --output text)" \
            --paths '/*'
