name: GitHub Pages CI
on: [pull_request, push]
jobs:
  build_and_deploy:
    name: Build site with Zola and deploy
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: verify
    steps:
      - uses: actions/checkout@v2
      - name: Install Zola
        run: sudo snap install --edge zola
      - name: Build site
        run: zola build
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@1.3.0
        with:
          # Your Cloudflare API Token
          apiToken: ${{ secrets.CF_API_TOKEN }}
